---

- name: "Deploy code"
  hosts: all
  become: yes
  become_user: root
  remote_user: "{{ remote_user }}"
  vars:
    autograder_home: "/home/{{ autograder_user }}"
    autograder_src_path: "{{ autograder_home }}/comp310-autograder"
  tasks:
    - name: "Add gcc-11 ppa to be on par with Mimi gcc version"
      ansible.builtin.apt_repository:
        repo: ppa:ubuntu-toolchain-r/test
        state: present
    - name: "Ensure dependencies are installed"
      ansible.builtin.apt:
        name:
          - git
          - strace
          - python3
          - bubblewrap
          - gcc-11
        state: present
        update_cache: yes
    - name: "Create autograder user"
      ansible.builtin.user:
        name: "{{ autograder_user }}"
        generate_ssh_key: yes
        create_home: yes
        system: yes
        state: present
    - name: "Fetch latest version"
      become_user: "{{ autograder_user }}"
      vars:
        ansible_remote_tmp: "/tmp/comp310-autograder/.ansible"
      ansible.builtin.git:
        repo: "https://oauth2:{{ autograder_gitlab_token }}@{{ gitlab_url }}/{{ autograder_gitlab_path }}.git"
        dest: "{{ autograder_src_path }}"
        force: yes
    - name: Install specified python requirements
      ansible.builtin.pip:
        requirements: "{{ autograder_src_path }}/requirements.txt"
    - name: "Ensure cron entry exists"
      ansible.builtin.cron:
        name: "run comp310 autograder"
        minute: "11" # kinda random just in case we collide with other tasks
        hour: "5" # servers are in utc
        job: "cd {{ autograder_src_path }} && python3 -m autograder >> {{ autograder_home }}/autograder-err.log 2>&1"
        user: "{{ autograder_user }}"
